# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [47]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import json

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [30]:
csv_path = "weather_check.csv"
weather_check_df = pd.read_csv(csv_path)
weather_data_df = weather_check_df.drop("Unnamed: 0", 1)
weather_data_df

,Latitude,Longitude,City,Country Code,Max Temp,Humidity,Cloudiness,Wind Speed,Date
0,-16.4833,-151.7500,faanui,pf,81.63,70.0,100.0,4.14,1.619749e+09
1,77.4840,-69.3632,qaanaaq,gl,25.36,62.0,100.0,10.04,1.619749e+09
2,37.4636,-122.4286,half moon bay,us,63.00,82.0,1.0,10.36,1.619749e+09
3,-23.1203,-134.9692,rikitea,pf,77.05,63.0,77.0,12.84,1.619749e+09
4,66.0449,-17.3389,husavik,is,35.60,80.0,90.0,5.75,1.619749e+09
...,...,...,...,...,...,...,...,...,...
543,55.0000,25.7833,pabrade,lt,48.99,93.0,75.0,11.50,1.619750e+09
544,37.2651,35.6572,imamoglu,tr,66.99,94.0,0.0,3.44,1.619750e+09
545,66.1451,-65.7125,pangnirtung,ca,31.37,74.0,100.0,6.11,1.619750e+09
546,55.7028,37.3822,marfino,ru,45.00,61.0,0.0,6.71,1.619750e+09
547,40.1667,21.8167,aiani,gr,51.80,93.0,2.0,2.06,1.619750e+09

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [32]:
gmaps.configure(api_key=g_key)

In [34]:
locations = weather_data_df[["Latitude", "Longitude"]].astype(float)

humidity_percent = weather_data_df["Humidity"].astype(float)

In [35]:
fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights=humidity_percent, 
                                 dissipating=False, max_intensity=100,
                                 point_radius = 1)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [42]:
temperature_df = weather_data_df[(weather_data_df["Max Temp"]>=70)&(weather_data_df["Max Temp"]<=80)]
wind_speed_df = temperature_df[(temperature_df["Wind Speed"]<10)]
vacation_weather_df = wind_speed_df[(wind_speed_df["Cloudiness"]==0)]
vacation_weather_df

,Latitude,Longitude,City,Country Code,Max Temp,Humidity,Cloudiness,Wind Speed,Date
136,33.3406,44.4009,baghdad,iq,73.40,38.0,0.0,6.91,1.619749e+09
148,16.2526,-61.2741,saint-francois,gp,75.20,88.0,0.0,2.30,1.619750e+09
195,27.2574,33.8129,hurghada,eg,77.00,16.0,0.0,6.91,1.619750e+09
196,-23.8650,35.3833,inhambane,mz,71.98,77.0,0.0,5.53,1.619749e+09
299,23.9167,-106.9000,la cruz,mx,70.00,81.0,0.0,1.01,1.619750e+09
381,4.9333,-52.3333,cayenne,gf,78.01,100.0,0.0,4.29,1.619749e+09
394,5.1552,-52.6478,kourou,gf,78.01,100.0,0.0,3.22,1.619750e+09
512,24.6877,46.7219,riyadh,sa,73.40,27.0,0.0,3.44,1.619749e+09
540,12.4850,-16.5469,oussouye,sn,73.40,83.0,0.0,4.61,1.619750e+09

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [65]:
hotel_df = vacation_weather_df.reset_index(drop=True)
hotel_df["Hotel Name"] = ""
hotel_df

,Latitude,Longitude,City,Country Code,Max Temp,Humidity,Cloudiness,Wind Speed,Date,Hotel Name
0,33.3406,44.4009,baghdad,iq,73.40,38.0,0.0,6.91,1.619749e+09,
1,16.2526,-61.2741,saint-francois,gp,75.20,88.0,0.0,2.30,1.619750e+09,
2,27.2574,33.8129,hurghada,eg,77.00,16.0,0.0,6.91,1.619750e+09,
3,-23.8650,35.3833,inhambane,mz,71.98,77.0,0.0,5.53,1.619749e+09,
4,23.9167,-106.9000,la cruz,mx,70.00,81.0,0.0,1.01,1.619750e+09,
5,4.9333,-52.3333,cayenne,gf,78.01,100.0,0.0,4.29,1.619749e+09,
6,5.1552,-52.6478,kourou,gf,78.01,100.0,0.0,3.22,1.619750e+09,
7,24.6877,46.7219,riyadh,sa,73.40,27.0,0.0,3.44,1.619749e+09,
8,12.4850,-16.5469,oussouye,sn,73.40,83.0,0.0,4.61,1.619750e+09,

In [66]:
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
params = {
    "radius": 100000,
    "type": "hotel",
    "keyword": "hotel",
    "key": g_key,
}

for index, row in hotel_df.iterrows():
    lat = row["Latitude"]
    lng = row["Latitude"]
    
    params["location"] = f"{lat},{lng}"
    
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    hotel_name = requests.get(base_url, params=params)
    
    hotel_name = hotel_name.json()
    
    print(json.dumps(hotel_name, indent=4, sort_keys=True))
    
    try:
        hotel_df.loc[index, "Hotel Name"] = hotel_name["results"][0]["name"]

    except (KeyError, IndexError):
        print("Missing field/result... skipping.")
        
hotel_df

{
    "html_attributions": [],
    "results": [],
    "status": "ZERO_RESULTS"
}
Missing field/result... skipping.
{
    "html_attributions": [],
    "results": [],
    "status": "ZERO_RESULTS"
}
Missing field/result... skipping.
{
    "html_attributions": [],
    "results": [],
    "status": "ZERO_RESULTS"
}
Missing field/result... skipping.
{
    "html_attributions": [],
    "results": [],
    "status": "ZERO_RESULTS"
}
Missing field/result... skipping.
{
    "html_attributions": [],
    "results": [],
    "status": "ZERO_RESULTS"
}
Missing field/result... skipping.
{
    "html_attributions": [],
    "results": [],
    "status": "ZERO_RESULTS"
}
Missing field/result... skipping.
{
    "html_attributions": [],
    "results": [
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": 5.3509707,
                    "lng": 5.5066242
                },
                "viewport": {
                    "northeast": {
                        "lat": 5.35234437989272,
                        "lng": 5.508072129892722
                    },
                    "southwest": {
                        "lat": 5.349644720107277,
                        "lng": 5.505372470107278
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Genesis HOTEL",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {
                    "height": 624,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/116706233201812887550\">Emmanuel Perevimone</a>"
                    ],
                    "photo_reference": "ATtYBwIcCQNytHFvjtdeL26lf8Uh1RNNGXcObzyWLnBJ7LCchc6R0Dds4ka2r6lTethP6xXGtoh6UCoSioyiHTFRb-2BKR1L0H8qKZoAgcDvUpj_Pp_Y6dySdRhtDqt-9XtXXNaVu-h9Qg5WzgBBOrp_t_u4zbHExJ8h4HRiqKe6eof1ouaR",
                    "width": 700
                }
            ],
            "place_id": "ChIJ627WtndrQBARzrEwDqBmhgc",
            "plus_code": {
                "compound_code": "9G24+9J Burutu, Nigeria",
                "global_code": "6FQ79G24+9J"
            },
            "rating": 3.6,
            "reference": "ChIJ627WtndrQBARzrEwDqBmhgc",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 17,
            "vicinity": "1 Jetty Road, LGA, Burutu"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": 5.3502149,
                    "lng": 5.342257500000001
                },
                "viewport": {
                    "northeast": {
                        "lat": 5.351527729892721,
                        "lng": 5.343699529892723
                    },
                    "southwest": {
                        "lat": 5.348828070107277,
                        "lng": 5.340999870107279
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png",
            "name": "Chally hotel",
            "photos": [
                {
                    "height": 3456,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/109755339661517649857\">Curious One</a>"
                    ],
                    "photo_reference": "ATtYBwIN8dnJ7WUlB0RZGwdys40FTVkhWaPWEfsHlY3DFcakLI_oh-HhTJqOGS8KQd1ye4TkLVrCEZhzdrcKA5El9SsonKLuDJTX_-9K8PHzXu4jhY-pEjtlBukc1eOcYusLsap-tDxsqDxGss6FM17aiwNHSwQwDjiDgFQIVAcguVyvNqxg",
                    "width": 4608
                }
            ],
            "place_id": "ChIJuaG2GNAVQBARJvkhZ210ogs",
            "plus_code": {
                "compound_code": "982R+3W Forcados, Nigeria",
                "global_code": "6FQ7982R+3W"
            },
            "rating": 4,
            "reference": "ChIJuaG2GNAVQBARJvkhZ210ogs",
            "scope": "GOOGLE",
            "types": [
                "lodging",
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 2,
            "vicinity": "Unnamed Road, Forcados"
        },
        {
            "business_status": "OPERATIONAL",
            "geometry": {
                "location": {
                    "lat": 5.3570831,
                    "lng": 5.347048399999999
                },
                "viewport": {
                    "northeast": {
                        "lat": 5.358465279892721,
                        "lng": 5.348190629892721
                    },
                    "southwest": {
                        "lat": 5.355765620107277,
                        "lng": 5.345490970107277
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png",
            "name": "Ogulagha Community",
            "opening_hours": {
                "open_now": true
            },
            "photos": [
                {
                    "height": 2268,
                    "html_attributions": [
                        "<a href=\"https://maps.google.com/maps/contrib/106578241166271854364\">A Google User</a>"
                    ],
                    "photo_reference": "ATtYBwLvkBEI5OPNVbhKoW8iE5Ndad6-n8bjFPl8-jyu8tdl_sCQNMTdszzMTS7LMScUqjw9z_-AWgd63_-7roYOK4S1bXwRdY8zDcRdvIBTHIUsXPKXqixYEj2rqURAZUFtXHQFvNyrQ19VnHz47rnzkuQwLaB1f1qbRQuPnPN_FoPA1I9U",
                    "width": 4032
                }
            ],
            "place_id": "ChIJ-3r5fNkUQBARsnP7o-YQGvk",
            "plus_code": {
                "compound_code": "984W+RR Forcados, Nigeria",
                "global_code": "6FQ7984W+RR"
            },
            "rating": 4.1,
            "reference": "ChIJ-3r5fNkUQBARsnP7o-YQGvk",
            "scope": "GOOGLE",
            "types": [
                "point_of_interest",
                "establishment"
            ],
            "user_ratings_total": 103,
            "vicinity": "Forcados"
        }
    ],
    "status": "OK"
}
{
    "html_attributions": [],
    "results": [],
    "status": "ZERO_RESULTS"
}
Missing field/result... skipping.
{
    "html_attributions": [],
    "results": [],
    "status": "ZERO_RESULTS"
}
Missing field/result... skipping.

,Latitude,Longitude,City,Country Code,Max Temp,Humidity,Cloudiness,Wind Speed,Date,Hotel Name
0,33.3406,44.4009,baghdad,iq,73.40,38.0,0.0,6.91,1.619749e+09,
1,16.2526,-61.2741,saint-francois,gp,75.20,88.0,0.0,2.30,1.619750e+09,
2,27.2574,33.8129,hurghada,eg,77.00,16.0,0.0,6.91,1.619750e+09,
3,-23.8650,35.3833,inhambane,mz,71.98,77.0,0.0,5.53,1.619749e+09,
4,23.9167,-106.9000,la cruz,mx,70.00,81.0,0.0,1.01,1.619750e+09,
5,4.9333,-52.3333,cayenne,gf,78.01,100.0,0.0,4.29,1.619749e+09,
6,5.1552,-52.6478,kourou,gf,78.01,100.0,0.0,3.22,1.619750e+09,Genesis HOTEL
7,24.6877,46.7219,riyadh,sa,73.40,27.0,0.0,3.44,1.619749e+09,
8,12.4850,-16.5469,oussouye,sn,73.40,83.0,0.0,4.61,1.619750e+09,

In [67]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

KeyError: 'Country'

In [70]:
hotel_options = hotel_df["Hotel Name"].tolist()

# Add marker layer ontop of heat map
marker_locations = hotel_df[['Latitude', 'Longitude']]

# Create a marker_layer using the poverty list to fill the info box
fig = gmaps.figure()
markers = gmaps.marker_layer(marker_locations,
    info_box_content=[f"Hotel Locations: {hotel}" for hotel in hotel_options])
fig.add_layer(markers)
fig

# Display figure

Figure(layout=FigureLayout(height='420px'))